-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS mandip_edu;
USE mandip_edu;

-- 1. Users Table
-- Stores learner profiles and authentication details
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. Syllabus Table
-- Stores the Curriculum Architect's generated learning pathways
CREATE TABLE IF NOT EXISTS syllabus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    assessed_level ENUM('Beginner', 'Intermediate', 'Advanced', 'Research') NOT NULL,
    overview_text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Modules Table
-- Breaks down the syllabus into sequential teaching modules
CREATE TABLE IF NOT EXISTS modules (
    id INT AUTO_INCREMENT PRIMARY KEY,
    syllabus_id INT NOT NULL,
    module_title VARCHAR(255) NOT NULL,
    sequence_order INT NOT NULL,
    module_content TEXT NOT NULL, -- The specific physics concepts, equations, analogues
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (syllabus_id) REFERENCES syllabus(id) ON DELETE CASCADE
);

-- 4. Quizzes Table
-- Stores assessments generated by the Assessment Designer
CREATE TABLE IF NOT EXISTS quizzes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    module_id INT NOT NULL,
    question_type ENUM('Conceptual', 'Numerical', 'Higher-Order') NOT NULL,
    question_text TEXT NOT NULL,
    correct_reference TEXT NOT NULL, -- Evaluation criteria or the correct answer
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
);

-- 5. Results Table
-- Tracks how well the user answered the quizzes
CREATE TABLE IF NOT EXISTS results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    quiz_id INT NOT NULL,
    user_answer TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    score_awarded DECIMAL(5,2), -- Useful if partial credit exists
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);

-- 6. Learning Progress Table
-- Tracks overall mastery driven by the Progress Analyst
CREATE TABLE IF NOT EXISTS learning_progress (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    current_level ENUM('Beginner', 'Intermediate', 'Advanced', 'Research') NOT NULL,
    progress_percentage DECIMAL(5,2) DEFAULT 0.00,
    modules_completed INT DEFAULT 0,
    last_recommendation VARCHAR(255), -- E.g., 'Advance to next module', 'Revise Newtonian Mechanics'
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 7. Session History Table
-- Logs the AI Multi-Agent interaction history for context memory
CREATE TABLE IF NOT EXISTS session_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    agent_id VARCHAR(100) NOT NULL, -- E.g., 'CurriculumArchitect', 'ResearchPhysicist'
    user_prompt TEXT,
    agent_response TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Note: Ensure MySQL is running locally and execute this script using:
-- mysql -u root -p < setup_database.sql
