-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS edugpt_db;
USE edugpt_db;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    learning_points INT DEFAULT 0,
    user_rank ENUM('Bronze Learner', 'Silver Scholar', 'Gold Achiever', 'Master Mentor') DEFAULT 'Bronze Learner',
    streak_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Courses Table (Stores user's learning path metadata)
CREATE TABLE IF NOT EXISTS courses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    level ENUM('Beginner', 'Intermediate', 'Advanced') NOT NULL,
    goal VARCHAR(255) DEFAULT 'General Learning',
    style VARCHAR(255) DEFAULT 'Standard',
    status ENUM('active', 'completed', 'archived') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Syllabus/Modules Table (Generated by Curriculum Agent)
CREATE TABLE IF NOT EXISTS syllabus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id INT NOT NULL,
    module_title VARCHAR(255) NOT NULL,
    module_order INT NOT NULL,
    learning_objectives TEXT,
    key_concepts TEXT,
    practical_task TEXT,
    mini_project TEXT,
    estimated_time VARCHAR(50),
    is_completed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- 4. Lessons Table (Content delivered by Instructor Agent)
CREATE TABLE IF NOT EXISTS lessons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    syllabus_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT, -- Stores the generated lesson text/HTML
    code_snippets LONGTEXT, -- Stores JSON or text of code examples
    summary TEXT,
    key_takeaways TEXT,
    completed_at TIMESTAMP NULL,
    FOREIGN KEY (syllabus_id) REFERENCES syllabus(id) ON DELETE CASCADE
);

-- 5. Assessments Table (Generated by Assessment Agent)
CREATE TABLE IF NOT EXISTS assessments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    syllabus_id INT NOT NULL, -- Assessments are per module usually
    questions_json JSON, -- Stores generated MCQs, Short Answer, Practical Task
    user_answers_json JSON,
    score INT DEFAULT 0,
    feedback TEXT, -- Detailed feedback from Evaluation Agent
    weak_areas TEXT,
    attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (syllabus_id) REFERENCES syllabus(id) ON DELETE CASCADE
);

-- 6. Analytics Logs (For Learning Analytics Agent)
CREATE TABLE IF NOT EXISTS analytics_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    action_type VARCHAR(50) NOT NULL, -- e.g., 'start_lesson', 'complete_quiz', 'login'
    action_details TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
